import type {RzdNode} from './nodes';
import type {DateString} from '#includes/DateString';

type StationInfo = {
  StationName: string,
  StationCode: string,
  CnsiCode: string,
  RegionName: string,
  IsoCode: string,
}

type AvailableBaggageType = {
  Type:
    | 'HandLuggage'
    | 'OversizedLuggage'
    | 'LuggageInBaggageRoom'
    | 'PetTransportation',
  Name:
    | 'Ручная кладь'
    | 'Негабаритный багаж'
    | 'Багаж в специально оборудованных купе'
    | 'Домашние животные',
  Description: null,
  CarBaggageInfo: null,
}

type Discount = {
  DiscountType:
    | 'Birthday'
    | 'BirthdayAccompanying'
    | 'InternalFamily'
    | 'UniversalCard'
    | 'BusinessTravelCard'
    | 'Pupil',
  Description: string,
}

type CarGroup = {
  Carriers: string[],
  CarrierDisplayNames: string[],
  ServiceClasses: string[],
  MinPrice: number,
  MaxPrice: number,
  CarType: string,
  CarTypeName: string,
  PlaceQuantity: number,
  LowerPlaceQuantity: number,
  UpperPlaceQuantity: number,
  LowerSidePlaceQuantity: number,
  UpperSidePlaceQuantity: number,
  MalePlaceQuantity: number,
  FemalePlaceQuantity: number,
  EmptyCabinQuantity: number,
  MixedCabinQuantity: number,
  IsSaleForbidden: boolean,
  AvailabilityIndication: string,
  CarDescriptions: Array<null | string>,
  ServiceClassNameRu: null,
  ServiceClassNameEn: null,
  InternationalServiceClasses: string[],
  ServiceCosts: number[],
  IsBeddingSelectionPossible: boolean,
  BoardingSystemTypes: string[],
  HasElectronicRegistration: boolean,
  HasGenderCabins: boolean,
  HasPlaceNumeration: boolean,
  HasPlacesNearPlayground: boolean,
  HasPlacesNearPets: boolean,
  HasPlacesForDisabledPersons: boolean,
  HasPlacesNearBabies: boolean,
  AvailableBaggageTypes: AvailableBaggageType[],
  HasNonRefundableTariff: boolean,
  Discounts: Discount[],
  AllowedTariffs: any[],
  InfoRequestSchema: string,
  TotalPlaceQuantity: number,
  PlaceReservationTypes: string[],
  IsThreeHoursReservationAvailable: boolean,
  IsMealOptionPossible: boolean,
  IsAdditionalMealOptionPossible: boolean,
  IsOnRequestMealOptionPossible: boolean,
  IsTransitDocumentRequired: boolean,
  IsInterstate: boolean,
  ClientFeeCalculation: null,
  AgentFeeCalculation: null,
  HasNonBrandedCars: boolean,
  TripPointQuantity: number,
  HasPlacesForBusinessTravelBooking: boolean,
  IsCarTransportationCoaches: boolean,
  IsGroupTransportaionAvailable: boolean,
  ServiceClassName: string,
  HasFssBenefit: boolean,
}

export type Train = {
  CarGroups: CarGroup[],
  IsFromSchedule: boolean,
  IsTourPackagePossible: boolean,
  CarTransportationsFreePlacesCount: null,
  ActualMovement: null,
  CategoryId: null,
  ScheduleId: null,
  BaggageCarsThreads: string[],
  CarTransportationCoachesThreads: null,
  Provider: string,
  IsWaitListAvailable: boolean,
  HasElectronicRegistration: boolean,
  HasCarTransportationCoaches: boolean,
  HasDynamicPricingCars: boolean,
  HasTwoStoreyCars: boolean,
  HasSpecialSaleMode: boolean,
  Carriers: string[],
  CarrierDisplayNames: string[],
  Id: number,
  IsBranded: boolean,
  TrainNumber: string,
  TrainNumberToGetRoute: string,
  DisplayTrainNumber: string,
  TrainDescription: string,
  TrainName: string,
  TrainNameEn: string,
  TransportType: string,
  OriginName: string,
  InitialStationName: string,
  OriginStationCode: string,
  OriginStationInfo: StationInfo,
  InitialTrainStationInfo: StationInfo,
  InitialTrainStationCode: string,
  InitialTrainStationCnsiCode: string,
  DestinationName: string,
  FinalStationName: string,
  DestinationStationCode: string,
  DestinationStationInfo: StationInfo,
  FinalTrainStationInfo: StationInfo,
  FinalTrainStationCode: string,
  FinalTrainStationCnsiCode: string,
  DestinationNames: string[],
  FinalStationNames: string[],
  DepartureDateTime: DateString,
  LocalDepartureDateTime: DateString,
  ArrivalDateTime: DateString,
  LocalArrivalDateTime: DateString,
  ArrivalDateTimes: DateString[],
  LocalArrivalDateTimes: DateString[],
  DepartureDateFromFormingStation: DateString,
  DepartureStopTime: number,
  ArrivalStopTime: number,
  TripDuration: number,
  TripDistance: number,
  IsSuburban: boolean,
  IsComponent: boolean,
  CarServices: any[],
  IsSaleForbidden: boolean,
  IsTicketPrintRequiredForBoarding: boolean,
  BookingSystem: string,
  IsVrStorageSystem: boolean,
  PlacesStorageType: string,
  BoardingSystemTypes: string[],
  TrainBrandCode: null,
  TrainClassNames: null,
  ServiceProvider: string,
  DestinationStationName: string,
  OriginStationName: string,
  IsPlaceRangeAllowed: boolean,
  IsTrainRouteAllowed: boolean,
}

export type TrainPricing = {
  OriginStationCode: string,
  DestinationStationCode: string,
  Trains: Train[],
  ClientFeeCalculation: null,
  AgentFeeCalculation: null,
  OriginCode: string,
  OriginStationInfo: StationInfo,
  OriginTimeZoneDifference: number,
  DestinationCode: string,
  DestinationStationInfo: StationInfo,
  DestinationTimeZoneDifference: number,
  RoutePolicy: string,
  DepartureTimeDescription: string,
  ArrivalTimeDescription: string,
  IsFromUkrain: boolean,
  NotAllTrainsReturned: boolean,
  BookingSystem: string,
  Id: number,
  DestinationStationName: string,
  OriginStationName: string,
  MoscowDateTime: DateString,
}

export type TrainPricingProps = {
  from: RzdNode<'station'>['nodeId'],
  to: RzdNode<'station'>['nodeId'],
  date: string,
}